"""empty message

Revision ID: 13fdb8bb23b7
Revises: e93ffe94b4d9
Create Date: 2019-06-18 13:20:23.074499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13fdb8bb23b7'
down_revision = 'e93ffe94b4d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atk_sg',
    sa.Column('attacker_id', sa.Integer(), nullable=True),
    sa.Column('softgoal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attacker_id'], ['attacker.id'], ),
    sa.ForeignKeyConstraint(['softgoal_id'], ['soft_goal.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atk_sg')
    # ### end Alembic commands ###
