"""empty message

Revision ID: 14b9ebbf3fce
Revises: 9acf862fd7c2
Create Date: 2019-07-24 12:58:02.732520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14b9ebbf3fce'
down_revision = '9acf862fd7c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'hard_goal', 'sub_service', ['services'], ['id'])
    op.drop_column('hard_goal', 'applications')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hard_goal', sa.Column('applications', mysql.VARCHAR(length=280), nullable=True))
    op.drop_constraint(None, 'hard_goal', type_='foreignkey')
    # ### end Alembic commands ###
