"""empty message

Revision ID: 573d4df2a35f
Revises: 3da8ac1be9a3
Create Date: 2019-10-14 15:16:20.535387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '573d4df2a35f'
down_revision = '3da8ac1be9a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bb_mechanisms', 'extra_hg')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bb_mechanisms', sa.Column('extra_hg', mysql.VARCHAR(length=280), nullable=True))
    # ### end Alembic commands ###
