"""empty message

Revision ID: 711067bc74d8
Revises: 56b9b0ff9545
Create Date: 2019-10-15 16:28:41.520732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '711067bc74d8'
down_revision = '56b9b0ff9545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bb_mechanisms', 'extra_softgoal')
    op.drop_column('bb_mechanisms', 'extra_functional_requirement')
    op.drop_column('bb_mechanisms', 'extra_asset')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bb_mechanisms', sa.Column('extra_asset', mysql.VARCHAR(length=280), nullable=True))
    op.add_column('bb_mechanisms', sa.Column('extra_functional_requirement', mysql.VARCHAR(length=280), nullable=True))
    op.add_column('bb_mechanisms', sa.Column('extra_softgoal', mysql.VARCHAR(length=280), nullable=True))
    # ### end Alembic commands ###
