"""empty message

Revision ID: 761a6f88d49d
Revises: 9fa7d695e65b
Create Date: 2019-10-15 17:04:00.626734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761a6f88d49d'
down_revision = '9fa7d695e65b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extra_freq_req',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('bbm_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bbm_id'], ['bb_mechanisms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extra_soft_goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('bbm_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bbm_id'], ['bb_mechanisms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extra_soft_goal')
    op.drop_table('extra_freq_req')
    # ### end Alembic commands ###
