"""empty message

Revision ID: 8ead3ea6a9c8
Revises: c10089aac0ca
Create Date: 2019-07-16 16:23:03.296868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ead3ea6a9c8'
down_revision = 'c10089aac0ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor_details', sa.Column('role', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'actor_details', 'actors', ['role'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actor_details', type_='foreignkey')
    op.drop_column('actor_details', 'role')
    # ### end Alembic commands ###
