"""empty message

Revision ID: 9acf862fd7c2
Revises: 6439f5cd5b99
Create Date: 2019-07-23 12:30:34.137782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9acf862fd7c2'
down_revision = '6439f5cd5b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('act_atk',
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('attacker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['aktoren.id'], ),
    sa.ForeignKeyConstraint(['attacker_id'], ['attacker.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('act_atk')
    # ### end Alembic commands ###
