"""empty message

Revision ID: 9fa7d695e65b
Revises: 711067bc74d8
Create Date: 2019-10-15 16:35:18.970581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa7d695e65b'
down_revision = '711067bc74d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extra_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('bbm_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bbm_id'], ['bb_mechanisms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extra_asset')
    # ### end Alembic commands ###
