"""empty message

Revision ID: a4d1c11b3673
Revises: 692ee18830d4
Create Date: 2019-07-16 15:48:34.808118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d1c11b3673'
down_revision = '692ee18830d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor_component',
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['aktoren.id'], ),
    sa.ForeignKeyConstraint(['component_id'], ['sub_service.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actor_component')
    # ### end Alembic commands ###
