"""empty message

Revision ID: a7bee1d1ceff
Revises: ba124f817598
Create Date: 2019-09-06 17:08:56.749956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7bee1d1ceff'
down_revision = 'ba124f817598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hard_goal', sa.Column('freq_id', sa.Integer(), nullable=True))
    op.add_column('hard_goal', sa.Column('sg_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hard_goal', 'functional_requirement', ['freq_id'], ['id'])
    op.create_foreign_key(None, 'hard_goal', 'soft_goal', ['sg_id'], ['id'])
    op.drop_constraint('soft_goal_ibfk_1', 'soft_goal', type_='foreignkey')
    op.drop_column('soft_goal', 'hardgoal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soft_goal', sa.Column('hardgoal_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('soft_goal_ibfk_1', 'soft_goal', 'hard_goal', ['hardgoal_id'], ['id'])
    op.drop_constraint(None, 'hard_goal', type_='foreignkey')
    op.drop_constraint(None, 'hard_goal', type_='foreignkey')
    op.drop_column('hard_goal', 'sg_id')
    op.drop_column('hard_goal', 'freq_id')
    # ### end Alembic commands ###
