"""empty message

Revision ID: c10089aac0ca
Revises: a4d1c11b3673
Create Date: 2019-07-16 16:17:20.677772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c10089aac0ca'
down_revision = 'a4d1c11b3673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['aktoren.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['sub_service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('actor_component')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor_component',
    sa.Column('actor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('component_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['aktoren.id'], name='actor_component_ibfk_1'),
    sa.ForeignKeyConstraint(['component_id'], ['sub_service.id'], name='actor_component_ibfk_2'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('actor_details')
    # ### end Alembic commands ###
