"""empty message

Revision ID: deaf8d411863
Revises: 34bc26fab26f
Create Date: 2019-06-25 16:15:45.305967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'deaf8d411863'
down_revision = '34bc26fab26f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bb_actors',
    sa.Column('bb_id', sa.Integer(), nullable=True),
    sa.Column('actors.id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actors.id'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['bb_id'], ['bb_mechanisms.id'], )
    )
    op.drop_column('bb_mechanisms', 'against_actor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bb_mechanisms', sa.Column('against_actor', mysql.VARCHAR(length=40), nullable=True))
    op.drop_table('bb_actors')
    op.drop_table('actors')
    # ### end Alembic commands ###
