"""empty message

Revision ID: e0ce183e82b2
Revises: 761a6f88d49d
Create Date: 2020-02-07 13:25:39.639373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ce183e82b2'
down_revision = '761a6f88d49d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hard_goal', sa.Column('correctly_implemented', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hard_goal', 'correctly_implemented')
    # ### end Alembic commands ###
