"""empty message

Revision ID: e6aacc90ab40
Revises: 14b9ebbf3fce
Create Date: 2019-07-24 13:06:39.135443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6aacc90ab40'
down_revision = '14b9ebbf3fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hard_goal', sa.Column('component_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hard_goal', 'sub_service', ['component_id'], ['id'])
    op.drop_column('hard_goal', 'services')
    op.drop_column('hard_goal', 'applications')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hard_goal', sa.Column('applications', mysql.VARCHAR(length=280), nullable=True))
    op.add_column('hard_goal', sa.Column('services', mysql.VARCHAR(length=280), nullable=True))
    op.drop_constraint(None, 'hard_goal', type_='foreignkey')
    op.drop_column('hard_goal', 'component_id')
    # ### end Alembic commands ###
